### ISSUE TITLE
关于 fdzh.org 网站维护的问题

### ISSUE THREAD

**Issue by ImBearChild** [fdzh/fdzh.github.io#7]
根据目前的内容看，网站的内容似乎有些年久失修？同时 Fedora 中文社区官方也有着自己的网站： zh.fedoracommunity.org 。

我想问一下网站的维护者对目前的情况有什么看法或规划吗？

**Comment by tvvocold** [comment]
你好，
fdzh.org 已不再维护，刚我做了下 301 跳转到 zh.fedoracommunity.org 了哈😄

$ curl -i https://www.fdzh.org 
HTTP/2 301
date: Mon, 05 Jul 2021 05:12:56 GMT
cache-control: max-age=3600
expires: Mon, 05 Jul 2021 06:12:56 GMT
location: https://zh.fedoracommunity.org/
